require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/assets/**/*'
    - 'config/**/*'
    - 'doc/**/*'
    - 'spec/**/*'
    - 'test/**/*'

Rails:
    Enabled: true

Style/Encoding:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/**/*'

Style/Next:
  Enabled: true

Metrics/AbcSize:
  Max: 50
