require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/assets/**/*'
    - 'config/**/*'
    - 'doc/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/**/*'
    - 'app/lib/dams/controller_helper.rb'

Rails:
    Enabled: true

Style/Encoding:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/**/*'

Style/ConditionalAssignment:
  Exclude:
    - 'app/helpers/*'

Layout/Tab:
  Exclude:
    - 'app/lib/dams/controller_helper.rb'
    
Style/Next:
  Enabled: true

Metrics/AbcSize:
  Max: 50

Metrics/LineLength:
  Max: 150