require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'app/assets/**/*'
    - 'config/**/*'
    - 'doc/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'

Rails:
    Enabled: true

Style/Encoding:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/**/*'

Style/Next:
  Enabled: true

Metrics/AbcSize:
  Max: 50

Metrics/LineLength:
  Max: 150

Rails/OutputSafety:
  Exclude:
    - 'app/helpers/dams_objects_helper.rb'

Style/SafeNavigation:
  Exclude:
    - 'app/helpers/dams_objects_helper.rb'
    - 'lib/dams/controller_helper.rb'
