class DAMS < RDF::Vocabulary("http://library.ucsd.edu/ontology/dams#")
  property :title
  property :subtitle
  property :relatedTitle
  property :type
  property :date
  property :beginDate
  property :endDate
  property :language
  property :typeOfResource
  property :otherResource
  property :RelatedResource
  property :description
  property :uri
  property :relationship
  property :Relationship
  property :role
  property :name
  property :conferenceName
  property :corporateName
  property :familyName
  property :personalName
  property :elementList
  property :assembledCollection
  property :AssembledCollection
  property :provenanceCollection
  property :ProvenanceCollection
  property :provenanceCollectionPart
  property :ProvenanceCollectionPart
  property :Object
  property :collection
  property :preferredCitationNote
  property :PreferredCitationNote
  property :custodialResponsibilityNote
  property :CustodialResponsibilityNote
  property :scopeContentNote
  property :ScopeContentNote
  property :displayLabel
  property :subject
  property :complexSubject
  property :builtWorkPlace
  property :culturalContext
  property :CulturalContextElement
  property :function
  property :FunctionElement
  property :genreForm
  property :geographic
  property :iconography
  property :IconographyElement
  property :occupation
  property :scientificName
  property :ScientificNameElement
  property :stylePeriod
  property :StylePeriodElement
  property :technique
  property :TechniqueElement
  property :temporal
  property :topic
  property :rightsHolder
  property :Unit
  property :unit
  property :unitName
  property :unitGroup
  property :unitURI
  property :unitDescription
  property :copyright
  property :Copyright
  property :copyrightStatus
  property :copyrightJurisdiction
  property :copyrightPurposeNote
  property :copyrightNote
  property :statute
  property :Statute
  property :statuteCitation
  property :statuteJurisdiction
  property :statuteNote
  property :permission
  property :restriction
  property :Permission
  property :Restriction
  property :license
  property :License
  property :licenseNote
  property :licenseURI
  property :otherRights
  property :OtherRights
  property :otherRightsBasis
  property :otherRightsNote
  property :otherRightsURI
  property :code
  property :valueURI
  property :vocabulary
  property :component
  property :Component
  property :filestore
  property :file
  property :File
  property :sourcePath
  property :sourceFileName
  property :formatName
  property :formatVersion
  property :mimeType
  property :use
  property :size
  property :crc32checksum
  property :md5checksum
  property :sha1checksum
  property :sha256checksum
  property :sha512checksum
  property :dateCreated
  property :objectCategory
  property :compositionLevel
  property :preservationLevel
  property :quality
  property :hasComponent
  property :hasFile
  property :note
  property :Note
  property :hasAssembledCollection
  property :hasProvenanceCollection
  property :hasObject
  property :hasPart
  property :relatedCollection
  property :authority
  property :authorityURI  
  property :scannerManufacturer
  property :sourceType
  property :scannerModelName
  property :imageProducer
  property :scanningSoftwareVersion
  property :scanningSoftware
  property :captureSource
  property :SourceCapture
  property :sourceCapture
  property :BuiltWorkPlaceElement
  property :cartographics
  property :Cartographics
  property :point
  property :line
  property :polygon
  property :projection
  property :referenceSystem
  property :scale
  property :eventDate
  property :outcome
  property :DAMSEvent
  property :event
  property :partNumber
  property :partName
  property :nonSort  
end
