class DAMS < RDF::Vocabulary("http://library.ucsd.edu/ontology/dams#")
  property :title
  property :subtitle
  property :relatedTitle
  property :type
  property :date
  property :beginDate
  property :endDate
  property :language
  property :typeOfResource
  property :otherResource
  property :RelatedResource
  property :description
  property :uri
  property :relationship
  property :Relationship
  property :role
  property :name
  property :assembledCollection
  property :Object
  property :collection
  property :scopeContentNote
  property :displayLabel
  property :subject
  property :repositoryName
  property :repositoryURI
  property :repositoryDescription
  property :copyright
  property :Copyright
  property :copyrightStatus
  property :copyrightJurisdiction
  property :copyrightPurposeNote
  property :copyrightNote
  property :statute
  property :Statute
  property :statuteCitation
  property :statuteJurisdiction
  property :statuteNote
  property :permission
  property :restriction
  property :Permission
  property :Restriction
  property :license
  property :License
  property :licenseNote
  property :licenseURI
  property :otherRights
  property :OtherRights
  property :otherRightsBasis
  property :otherRightsNote
  property :otherRightsURI
  property :code
  property :valueURI
  property :vocabulary
  property :component
  property :Component
  property :file
  property :File
  property :sourcePath
  property :sourceFileName
  property :formatName
  property :formatVersion
  property :mimeType
  property :use
  property :size
  property :crc32checksum
  property :md5checksum
  property :sha1checksum
  property :sha256checksum
  property :sha512checksum
  property :dateCreated
  property :objectCategory
  property :compositionLevel
  property :preservationLevel
  property :quality
  property :hasComponent
  property :hasFile
  property :note
end
