class DAMS < RDF::Vocabulary("http://library.ucsd.edu/ontology/dams#")
  property :title
  property :relatedTitle
  property :type
  property :date
  property :beginDate
  property :endDate
  property :language
  property :typeOfResource
  property :otherResource
  property :RelatedResource
  property :description
  property :uri
  property :relationship
  property :Relationship
  property :role
  property :name
  property :assembledCollection
  property :Object
  property :value
  property :collection
  property :scopeContentNote
  property :displayLabel
  property :subject
  property :repositoryName
  property :repositoryURI
  property :repositoryDescription
  property :copyright
  property :Copyright
  property :copyrightStatus
  property :copyrightJurisdiction
  property :copyrightPurposeNote
  property :copyrightNote
  property :statute
  property :Statute
  property :statuteCitation
  property :statuteJurisdiction
  property :statuteNote
  property :permission
  property :restriction
  property :Permission
  property :Restriction
end
