# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

development:
  <<: *default

pontos:
  <<: *default
  adapter: postgresql
  database: <%= ENV.fetch('APPS_DHH_PONTOS_DB') {'default'}%>
  host: <%= ENV.fetch('APPS_DHH_PONTOS_DB_HOST') {'default'}%>
  username: <%= ENV.fetch('APPS_DHH_PONTOS_DB_USER') {'default'}%>
  password: <%= ENV.fetch('APPS_DHH_PONTOS_DB_PASS') {'default'}%>

gimili:
  <<: *default
  adapter: postgresql
  database: <%= ENV.fetch('APPS_DHH_GIMILI_DB') {'default'}%>
  host: <%= ENV.fetch('APPS_DHH_GIMILI_DB_HOST') {'default'}%>
  username: <%= ENV.fetch('APPS_DHH_GIMILI_DB_USER') {'default'}%>
  password: <%= ENV.fetch('APPS_DHH_GIMILI_DB_PASS') {'default'}%>

staging:
  <<: *default
  adapter: postgresql
  database: <%= ENV.fetch('APPS_DHH_STAGING_DB') {'default'}%>
  host: <%= ENV.fetch('APPS_DHH_STAGING_DB_HOST') {'default'}%>
  username: <%= ENV.fetch('APPS_DHH_STAGING_DB_USER') {'default'}%>
  password: <%= ENV.fetch('APPS_DHH_STAGING_DB_PASS') {'default'}%>

qa:
  <<: *default
  adapter: postgresql
  database: <%= ENV.fetch('APPS_DHH_QA_DB') {'default'}%>
  host: <%= ENV.fetch('APPS_DHH_QA_DB_HOST') {'default'}%>
  username: <%= ENV.fetch('APPS_DHH_QA_DB_USER') {'default'}%>
  password: <%= ENV.fetch('APPS_DHH_QA_DB_PASS') {'default'}%>

demo:
  <<: *default

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  database: <%= ENV.fetch('APPS_DHH_PROD_DB') {'default'}%>
  host: <%= ENV.fetch('APPS_DHH_PROD_DB_HOST') {'default'}%>
  username: <%= ENV.fetch('APPS_DHH_PROD_DB_USER') {'default'}%>
  password: <%= ENV.fetch('APPS_DHH_PROD_DB_PASS') {'default'}%>
