---
- creator
- director
- project director
- lead
- author
- principal investigator
- co-principal investigator
- research team head
- field director
- laboratory director
- researcher
- research team member
- analyst
- data contributor
- data manager
- field assistant
- laboratory assistant
- photographer
- advisor
- thesis advisor
- contributor
