key:
  - AGENTWORKRELATION
  - AgentWorkRelation      
  - CONTRIBUTOR
  - CREATOR
  - Contributor
  - Creator
  - FUNDER
  - Funder
  - HOST
  - Host
  - PRINCIPALINVESTIGATOR
  - PRINCIPALINVESTIGATORCONTACT
  - PUBLISHER
  - PrincipalInvestigator
  - PrincipalInvestigatorContact
  - Publisher
  - agentworkrelation
  - contributor
  - creator
  - funder
  - host
  - principalinvestigator
  - principalinvestigatorcontact
  - publisher
