require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AuditsController do

  # This should return the minimal set of attributes required to create a valid
  # Audit. As you add validations to Audit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "description" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AuditsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "authenticated" do
    before do
      sign_in User.create!( {:provider => 'developer'} )
    end

    describe "GET index" do
      it "assigns all audits as @audits" do
        audit = Audit.create! valid_attributes
        get :index, {}, valid_session
        assigns(:audits).should eq([audit])
      end
    end

    describe "GET show" do
      it "assigns the requested audit as @audit" do
        audit = Audit.create! valid_attributes
        get :show, {:id => audit.to_param}, valid_session
        assigns(:audit).should eq(audit)
      end
    end

  end

end
