class DamsProvenanceCollectionPart < ActiveFedora::Base
  include Hydra::AccessControls::Permissions

  has_metadata 'damsMetadata', :type => DamsProvenanceCollectionPartDatastream 
  has_attributes :assembledCollection, 
    :beginDate,
    :builtWorkPlace_attributes,
    :builtWorkPlace,
    :complexSubject_attributes,
    :complexSubject,
    :conferenceName_attributes,
    :conferenceName,
    :corporateName_attributes,
    :corporateName,
    :creatorURI,
    :culturalContext_attributes,
    :culturalContext,
    :custodialResponsibilityNote,
    :custodialResponsibilityNote_attributes,
    :date_attributes,
    :date,
    :dateValue,
    :endDate,
    :event,
    :familyName_attributes, 
    :familyName,
    :file_attributes,
    :file,
    :function_attributes,
    :function,
    :genreForm_attributes,
    :genreForm,
    :geographic_attributes,
    :geographic,
    :iconography_attributes,
    :iconography,
    :language_attributes,
    :language,
    :languageURI,
    :license_attributes, 
    :license,
    :licenseURI,
    :name_attributes,
    :name,
    :nameType,
    :nameURI,
    :note_attributes,
    :note,
    :noteDisplayLabel, 
    :noteType, 
    :occupation_attributes, 
    :occupation,
    :otherRights_attributes,
    :otherRights, 
    :otherRightsURI,
    :personalName_attributes,
    :personalName,
    :preferredCitationNote,
    :preferredCitationNote_attributes,
    :relResourceURI,
    :relatedResource_attributes,
    :relatedResource,
    :relatedResourceDescription, 
    :relatedResourceType, 
    :relatedResourceUri, 
    :relationship_attributes,
    :relationship,
    :relationshipNameType, 
    :relationshipNameURI, 
    :relationshipRoleURI,
    #:role,
    #:role_attributes,
    :scientificName_attributes,
    :scientificName,
    :scopeContentNote_attributes,
    :scopeContentNote,
    :simpleSubjectURI, 
    :sourceCapture,
    :statute_attributes,
    :statute,
    :statuteURI,
    :stylePeriod_attributes,
    :stylePeriod,
    :subject,
    :subjectType,
    :subjectURI,
    :subtitle,
    :technique_attributes,
    :technique,
    :temporal_attributes,
    :temporal,
    :title_attributes,    
    :title,
    :titleNonSort,
    :titlePartName,
    :titlePartNumber,
    :titleValue,
    :titleVariant,
    :titleTranslationVariant,
    :titleAbbreviationVariant,
    :titleAcronymVariant,
    :titleExpansionVariant,
    :topic_attributes,
    :topic,
    :typeOfResource,
    :resource_type,
    :provenanceCollection_attributes,
    :provenanceCollection, 
    :provenanceCollectionURI,
    :provenanceCollectionPart, 
    :provenanceCollection_node,
    :unit_attributes,
    :unit,
    :unitURI,
    :visibility,
      datastream: :damsMetadata, multiple: true

  def collections
    damsMetadata.load_collection damsMetadata.collection,damsMetadata.assembledCollection,damsMetadata.provenanceCollection,damsMetadata.provenanceCollectionPart
  end

 def provenanceCollections
    damsMetadata.load_provenanceCollections damsMetadata.provenanceCollection
  end

end 
